# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HuStmpHrrr
email: fdhzs2010@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome! Still experimental.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hustmphrrr.github.io" # the base hostname & protocol for your site
twitter_username: JasonHuZS
github_username:  HuStmpHrrr

# Build settings
markdown: kramdown
